-------------------------------------------------------
-- DO NOT EDIT THIS FILE EVER
-- DOING SO MAY RESULT IN CRASHES AND UPGRADE PROBLEMS
-------------------------------------------------------

OpenScript( "includes/defines.lua" );
OpenScript( "includes/eventhook.lua" ); 		-- For event hooking
OpenScript( "includes/concom.lua" ); 			-- Console command emulation
OpenScript( "includes/util.lua" ); 

OpenScript( "includes/util_sprite2d.lua" );